version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - foodgram:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  web:
    image: flomixon/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  foodgram:
  static_value:
  media_value:

  
