# Generated by Django 2.2.16 on 2023-03-22 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230319_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#([A-F0-9]{6})$')], verbose_name='Цвет в HEX'),
        ),
    ]
